// Code generated by mockery v2.20.0. DO NOT EDIT.

package mockStorage

import (
	favorite "github.com/evgeniy-dammer/marketplace-api/internal/domain/favorite"
	context "github.com/evgeniy-dammer/marketplace-api/pkg/context"

	mock "github.com/stretchr/testify/mock"

	query "github.com/evgeniy-dammer/marketplace-api/pkg/query"
)

// Favorite is an autogenerated mock type for the Favorite type
type Favorite struct {
	mock.Mock
}

// FavoriteCreate provides a mock function with given fields: ctx, meta, _a2
func (_m *Favorite) FavoriteCreate(ctx context.Context, meta query.MetaData, _a2 favorite.Favorite) error {
	ret := _m.Called(ctx, meta, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, favorite.Favorite) error); ok {
		r0 = rf(ctx, meta, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FavoriteDelete provides a mock function with given fields: ctx, meta, itemID
func (_m *Favorite) FavoriteDelete(ctx context.Context, meta query.MetaData, itemID string) error {
	ret := _m.Called(ctx, meta, itemID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, string) error); ok {
		r0 = rf(ctx, meta, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFavorite interface {
	mock.TestingT
	Cleanup(func())
}

// NewFavorite creates a new instance of Favorite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFavorite(t mockConstructorTestingTNewFavorite) *Favorite {
	mock := &Favorite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
