// Code generated by mockery v2.20.0. DO NOT EDIT.

package mockStorage

import (
	context "github.com/evgeniy-dammer/marketplace-api/pkg/context"
	mock "github.com/stretchr/testify/mock"

	query "github.com/evgeniy-dammer/marketplace-api/pkg/query"

	queryparameter "github.com/evgeniy-dammer/marketplace-api/pkg/queryparameter"

	role "github.com/evgeniy-dammer/marketplace-api/internal/domain/role"

	user "github.com/evgeniy-dammer/marketplace-api/internal/domain/user"
)

// User is an autogenerated mock type for the User type
type User struct {
	mock.Mock
}

// UserCreate provides a mock function with given fields: ctx, meta, input
func (_m *User) UserCreate(ctx context.Context, meta query.MetaData, input user.CreateUserInput) (string, error) {
	ret := _m.Called(ctx, meta, input)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, user.CreateUserInput) (string, error)); ok {
		return rf(ctx, meta, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, user.CreateUserInput) string); ok {
		r0 = rf(ctx, meta, input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.MetaData, user.CreateUserInput) error); ok {
		r1 = rf(ctx, meta, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserDelete provides a mock function with given fields: ctx, meta, userID
func (_m *User) UserDelete(ctx context.Context, meta query.MetaData, userID string) error {
	ret := _m.Called(ctx, meta, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, string) error); ok {
		r0 = rf(ctx, meta, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserGetAll provides a mock function with given fields: ctx, meta, params
func (_m *User) UserGetAll(ctx context.Context, meta query.MetaData, params queryparameter.QueryParameter) ([]user.User, error) {
	ret := _m.Called(ctx, meta, params)

	var r0 []user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, queryparameter.QueryParameter) ([]user.User, error)); ok {
		return rf(ctx, meta, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, queryparameter.QueryParameter) []user.User); ok {
		r0 = rf(ctx, meta, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.MetaData, queryparameter.QueryParameter) error); ok {
		r1 = rf(ctx, meta, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetAllRoles provides a mock function with given fields: ctx, meta, params
func (_m *User) UserGetAllRoles(ctx context.Context, meta query.MetaData, params queryparameter.QueryParameter) ([]role.Role, error) {
	ret := _m.Called(ctx, meta, params)

	var r0 []role.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, queryparameter.QueryParameter) ([]role.Role, error)); ok {
		return rf(ctx, meta, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, queryparameter.QueryParameter) []role.Role); ok {
		r0 = rf(ctx, meta, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]role.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.MetaData, queryparameter.QueryParameter) error); ok {
		r1 = rf(ctx, meta, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetOne provides a mock function with given fields: ctx, meta, userID
func (_m *User) UserGetOne(ctx context.Context, meta query.MetaData, userID string) (user.User, error) {
	ret := _m.Called(ctx, meta, userID)

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, string) (user.User, error)); ok {
		return rf(ctx, meta, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, string) user.User); ok {
		r0 = rf(ctx, meta, userID)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.MetaData, string) error); ok {
		r1 = rf(ctx, meta, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUpdate provides a mock function with given fields: ctx, meta, input
func (_m *User) UserUpdate(ctx context.Context, meta query.MetaData, input user.UpdateUserInput) error {
	ret := _m.Called(ctx, meta, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, query.MetaData, user.UpdateUserInput) error); ok {
		r0 = rf(ctx, meta, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUser interface {
	mock.TestingT
	Cleanup(func())
}

// NewUser creates a new instance of User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUser(t mockConstructorTestingTNewUser) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
