// Code generated by mockery v2.20.0. DO NOT EDIT.

package mockCache

import mock "github.com/stretchr/testify/mock"

// Favorite is an autogenerated mock type for the Favorite type
type Favorite struct {
	mock.Mock
}

type mockConstructorTestingTNewFavorite interface {
	mock.TestingT
	Cleanup(func())
}

// NewFavorite creates a new instance of Favorite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFavorite(t mockConstructorTestingTNewFavorite) *Favorite {
	mock := &Favorite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
