version: "3.9"

services:
  marketplace-cache:
    container_name: marketplace-cache
    image: redis:alpine
    network_mode: host
    hostname: cache
    restart: on-failure
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      #- REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    volumes:
      #- /path/to/your_redis.conf:/opt/bitnami/cache/mounted-etc/cache.conf
      - marketplace-cache:/bitnami/cache/data

  marketplace-db:
    container_name: marketplace-db
    image: postgres:alpine
    network_mode: host
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_DB=marketplace
      - POSTGRES_USER=marketplace
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - marketplace-db:/var/lib/postgresql/data

  marketplace-api:
    container_name: marketplace-api
    build: .
    network_mode: host
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - marketplace-db
      - marketplace-cache

  marketplace-tracing:
    container_name: marketplace-tracing
    image: jaegertracing/all-in-one:latest
    network_mode: host
    restart: on-failure
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    depends_on:
      - marketplace-api

volumes:
  marketplace-db:
    external: true
  marketplace-cache:
    external: true