version: "3.9"

services:
  marketplace-cache:
    container_name: marketplace-cache
    image: redis:alpine
    network_mode: host
    hostname: cache
    restart: always
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      #- REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    volumes:
      #- /path/to/your_redis.conf:/opt/bitnami/cache/mounted-etc/cache.conf
      - marketplace-cache:/bitnami/cache/data

  marketplace-db:
    container_name: marketplace-db
    image: postgres:alpine
    network_mode: host
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=marketplace
      - POSTGRES_USER=marketplace
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - marketplace-db:/var/lib/postgresql/data

  marketplace-api:
    container_name: marketplace-api
    build: .
    network_mode: host
    restart: always
    env_file:
      - .env
    depends_on:
      - marketplace-db
      - marketplace-cache

  marketplace-migrate:
    container_name: marketplace-migrate
    image: migrate/migrate:4
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./schema:/schema
    command: [ "-path", "./schema", "-database",  'storage://marketplace:${DB_PASSWORD}@0.0.0.0:5432/marketplace?sslmode=disable', "up" ]
    depends_on:
      - marketplace-db

  marketplace-tracing:
    container_name: marketplace-tracing
    image: jaegertracing/all-in-one:latest
    network_mode: host
    depends_on:
      - marketplace-api

volumes:
  marketplace-db:
    external: true
  marketplace-cache:
    external: true