// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllRequest) Reset()         { *m = FindAllRequest{} }
func (m *FindAllRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllRequest) ProtoMessage()    {}
func (*FindAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *FindAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllRequest.Unmarshal(m, b)
}
func (m *FindAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllRequest.Marshal(b, m, deterministic)
}
func (m *FindAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllRequest.Merge(m, src)
}
func (m *FindAllRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllRequest.Size(m)
}
func (m *FindAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllRequest proto.InternalMessageInfo

type FindAllResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllResponse) Reset()         { *m = FindAllResponse{} }
func (m *FindAllResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllResponse) ProtoMessage()    {}
func (*FindAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *FindAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllResponse.Unmarshal(m, b)
}
func (m *FindAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllResponse.Marshal(b, m, deterministic)
}
func (m *FindAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllResponse.Merge(m, src)
}
func (m *FindAllResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllResponse.Size(m)
}
func (m *FindAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllResponse proto.InternalMessageInfo

func (m *FindAllResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Status               bool     `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Item) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*FindAllRequest)(nil), "protos.FindAllRequest")
	proto.RegisterType((*FindAllResponse)(nil), "protos.FindAllResponse")
	proto.RegisterType((*Item)(nil), "protos.Item")
}

func init() {
	proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df)
}

var fileDescriptor_6007f868cf6553df = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0x34, 0xa9, 0x75, 0x5a, 0xa2, 0x0c, 0x52, 0x97, 0x9e, 0x96, 0x9c, 0xf6, 0x94,
	0x42, 0xc5, 0x8b, 0x37, 0x3d, 0x08, 0xbd, 0xae, 0x37, 0x6f, 0xd1, 0x0c, 0xb2, 0xd8, 0xfc, 0x69,
	0x66, 0x22, 0xf8, 0xed, 0x65, 0xb3, 0xb5, 0x20, 0x9e, 0x76, 0xde, 0xef, 0x2d, 0xbb, 0xef, 0x0d,
	0x80, 0x17, 0x6a, 0xca, 0x7e, 0xe8, 0xa4, 0xc3, 0xf9, 0x74, 0x70, 0x71, 0x0d, 0xf9, 0xb3, 0x6f,
	0xeb, 0xc7, 0xc3, 0xc1, 0xd1, 0x71, 0x24, 0x96, 0xe2, 0x1e, 0xae, 0xce, 0x84, 0xfb, 0xae, 0x65,
	0xc2, 0x02, 0xb2, 0xbd, 0x50, 0xc3, 0x5a, 0x99, 0x99, 0x5d, 0xee, 0x56, 0xf1, 0x0d, 0x2e, 0x03,
	0x74, 0xd1, 0x2a, 0x04, 0xd2, 0x30, 0x60, 0x0e, 0x89, 0xaf, 0xb5, 0x32, 0xca, 0x5e, 0xba, 0xc4,
	0xd7, 0x88, 0x90, 0xb6, 0x55, 0x43, 0x3a, 0x99, 0xc8, 0x34, 0xe3, 0x06, 0x16, 0xc7, 0xb1, 0x6a,
	0xc5, 0xcb, 0xb7, 0x9e, 0x19, 0x65, 0x33, 0x77, 0xd6, 0x78, 0x03, 0x59, 0x3f, 0xf8, 0x77, 0xd2,
	0xa9, 0x51, 0x56, 0xb9, 0x28, 0x70, 0x0d, 0x73, 0x96, 0x4a, 0x46, 0xd6, 0x99, 0x51, 0x76, 0xe1,
	0x4e, 0x6a, 0xb7, 0x87, 0x65, 0xf8, 0xf5, 0x85, 0x86, 0xaf, 0x70, 0xed, 0x01, 0x2e, 0x4e, 0xd9,
	0x71, 0xfd, 0x1b, 0xf2, 0x6f, 0xbd, 0xcd, 0xed, 0x3f, 0x1e, 0x4b, 0x3e, 0xe5, 0xaf, 0xab, 0x72,
	0xdb, 0x7f, 0x7e, 0x6c, 0xa3, 0xff, 0x16, 0x37, 0x74, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc0,
	0x8b, 0xa3, 0xb9, 0x36, 0x01, 0x00, 0x00,
}
