server:
  port: "1111"
  read_timeout: 60
  write_timeout: 60
  idle_timeout: 60
  max_header_bytes: 1048576

router:
  mode: "debug" # debug, release

database:
  host: "localhost"
  port: "5432"
  username: "emenu"
  dbname: "emenu"
  sslmode: "disable"

cache:
  mode: true # true, false
  host: "localhost"
  port: "6379"
  database: 0
