service:
  name: "emenu-api"
  production: false # true, false
  tracing: true # true, false
  cache: true # true, false
  router: "debug" # debug, release

server:
  port: "1111"
  read_timeout: 60
  write_timeout: 60
  idle_timeout: 60
  max_header_bytes: 1048576

database:
  host: "localhost"
  port: "5432"
  username: "emenu"
  dbname: "emenu"
  sslmode: "disable"
  timeout: 30

cache:
  host: "localhost"
  port: "6379"
  database: 0
  timeout: 30
  ttl: 20

tracing:
  url: "http://localhost:14268/api/traces"

migrations:
  directory: "./migrations"