service:
  name: "marketplace-api"
  production: false # true, false
  tracing: true # true, false
  cache: true # true, false
  router: "debug" # debug, release

server:
  port: "1111"
  read_timeout: 60
  write_timeout: 60
  idle_timeout: 60
  max_header_bytes: 1048576

database:
  master:
    host: "localhost"
    port: "5432"
    username: "marketplace"
    dbname: "marketplace"
    sslmode: "disable"
    timeout: 30

  slave:
    host: "localhost"
    port: "5432"
    username: "marketplace"
    dbname: "marketplace"
    sslmode: "disable"
    timeout: 30

cache:
  host: "localhost"
  port: "6379"
  database: 0
  timeout: 30
  ttl: 20

vault:
  address: "http://127.0.0.1:8200"

tracing:
  url: "http://localhost:14268/api/traces"

authentication:
  access_token_ttl: 20
  refresh_token_ttl: 720

migrations:
  directory: "./migrations"