server:
  port: "1111"
  readtimeout: 60
  writetimeout: 60
  idletimeout: 60
  maxheaderbytes: 1048576

router:
  mode: "debug" # debug, release

database:
  host: "localhost"
  port: "5432"
  username: "emenu"
  dbname: "emenu"
  sslmode: "disable"